const PRODUCTS = [
  { id: 1, name: "Cloud Sneakers", store: "General", cat: "Fashion", price: 89.0, emoji: "👟", bg: "#fde68a", desc: "Impossibly light. Walk on clouds, no refunds needed because nothing is real." },
  { id: 2, name: "Denim Jacket", store: "General", cat: "Fashion", price: 74.5, emoji: "🧥", bg: "#bfdbfe", desc: "A classic layer that goes with everything you already own." },
  { id: 3, name: "Sun Hat", store: "General", cat: "Fashion", price: 24.99, emoji: "👒", bg: "#fed7aa", desc: "Wide brim, big vibes." },
  { id: 4, name: "Round Sunglasses", store: "General", cat: "Fashion", price: 39.0, emoji: "🕶️", bg: "#ddd6fe", desc: "Main-character energy, UV protected." },
  { id: 5, name: "Wireless Headphones", store: "General", cat: "Tech", price: 149.99, emoji: "🎧", bg: "#c7d2fe", desc: "40-hour battery and noise cancelling for maximum daydreaming." },
  { id: 6, name: "Smart Watch", store: "General", cat: "Tech", price: 219.0, emoji: "⌚", bg: "#a7f3d0", desc: "Tracks steps, sleep and how many fake orders you've placed." },
  { id: 7, name: "Mechanical Keyboard", store: "General", cat: "Tech", price: 119.0, emoji: "⌨️", bg: "#fecaca", desc: "Clicky, satisfying, and totally overkill for email." },
  { id: 8, name: "Drone Camera", store: "General", cat: "Tech", price: 499.0, emoji: "🚁", bg: "#bae6fd", desc: "4K aerial shots of your imaginary vacation." },
  { id: 9, name: "Ceramic Plant Pot", store: "General", cat: "Home", price: 18.0, emoji: "🪴", bg: "#bbf7d0", desc: "Because every shelf needs a little green." },
  { id: 10, name: "Cozy Blanket", store: "General", cat: "Home", price: 45.0, emoji: "🛋️", bg: "#fbcfe8", desc: "Chunky knit. Sofa naps guaranteed." },
  { id: 11, name: "Scented Candle", store: "General", cat: "Home", price: 21.0, emoji: "🕯️", bg: "#fef08a", desc: "Notes of vanilla, cedar and a dash of impulse buy." },
  { id: 12, name: "Espresso Machine", store: "General", cat: "Home", price: 329.0, emoji: "☕", bg: "#e7d5c3", desc: "Café-quality shots at home." },
  { id: 13, name: "Board Game Classic", store: "General", cat: "Fun", price: 32.0, emoji: "🎲", bg: "#fca5a5", desc: "Friendships tested since forever." },
  { id: 14, name: "Acoustic Guitar", store: "General", cat: "Fun", price: 259.0, emoji: "🎸", bg: "#fdba74", desc: "Learn three chords, play a thousand songs." },
  { id: 15, name: "Retro Game Console", store: "General", cat: "Fun", price: 79.0, emoji: "🎮", bg: "#d8b4fe", desc: "500 built-in games and zero loading screens." },
  { id: 16, name: "Chocolate Box", store: "General", cat: "Treats", price: 15.5, emoji: "🍫", bg: "#d6b9a3", desc: "Twelve pieces. No judgment if it's gone in a day." },
  { id: 17, name: "Donut Dozen", store: "General", cat: "Treats", price: 12.0, emoji: "🍩", bg: "#fbcfe8", desc: "Glazed, sprinkled and dangerously fresh." },
  { id: 18, name: "Bubble Tea Kit", store: "General", cat: "Treats", price: 27.0, emoji: "🧋", bg: "#fde68a", desc: "Make boba at home with tapioca pearls and thick straws." },
  { id: 19, name: "Korean-Style Knit Cardigan", store: "Taobao", cat: "Fashion", price: 22.9, emoji: "🧶", bg: "#fbcfe8", desc: "Soft loose knit in a cropped fit, a Taobao-style bestseller silhouette." },
  { id: 20, name: "Y2K Pleated Mini Skirt", store: "Taobao", cat: "Fashion", price: 14.5, emoji: "👗", bg: "#ddd6fe", desc: "Pleated with built-in shorts and a high waist." },
  { id: 21, name: "Oversized Graphic Hoodie", store: "Taobao", cat: "Fashion", price: 26.8, emoji: "🧥", bg: "#c7d2fe", desc: "Heavyweight fleece with a big back print." },
  { id: 22, name: "Platform Mary Jane Shoes", store: "Taobao", cat: "Fashion", price: 31.0, emoji: "👞", bg: "#fecaca", desc: "Chunky sole, ankle strap, very cute." },
  { id: 23, name: "Mini Crossbody Chain Bag", store: "Taobao", cat: "Fashion", price: 18.9, emoji: "👜", bg: "#fde68a", desc: "Small enough for your phone and lip balm, fits the aesthetic." },
  { id: 24, name: "Tailored Oversized Blazer", store: "Zara", cat: "Fashion", price: 89.9, emoji: "🧥", bg: "#e7d5c3", desc: "Structured shoulders, single-button, in a crisp neutral." },
  { id: 25, name: "Wide-Leg Pleated Trousers", store: "Zara", cat: "Fashion", price: 49.9, emoji: "👖", bg: "#bfdbfe", desc: "High-rise fluid trousers with a sharp crease." },
  { id: 26, name: "Satin Slip Midi Dress", store: "Zara", cat: "Fashion", price: 59.9, emoji: "👗", bg: "#fbcfe8", desc: "Bias-cut with thin straps and a soft drape." },
  { id: 27, name: "Faux Leather Biker Jacket", store: "Zara", cat: "Fashion", price: 119.0, emoji: "🧥", bg: "#d6d3d1", desc: "Cropped moto jacket with silver hardware." },
  { id: 28, name: "Ribbed Knit Polo Top", store: "Zara", cat: "Fashion", price: 29.9, emoji: "👚", bg: "#bbf7d0", desc: "Fitted rib knit with a contrast collar." },
  { id: 29, name: "Cashmere Crewneck Sweater", store: "Nordstrom", cat: "Fashion", price: 149.0, emoji: "🧶", bg: "#fed7aa", desc: "Lightweight and luxuriously soft, for everyday wear." },
  { id: 30, name: "Classic Trench Coat", store: "Nordstrom", cat: "Fashion", price: 278.0, emoji: "🧥", bg: "#e7d5c3", desc: "Water-resistant double-breasted trench with a belt." },
  { id: 31, name: "Leather Ankle Boots", store: "Nordstrom", cat: "Fashion", price: 165.0, emoji: "🥾", bg: "#d6b9a3", desc: "Block heel, cushioned footbed, all-day comfy." },
  { id: 32, name: "Quilted Leather Tote", store: "Nordstrom", cat: "Fashion", price: 225.0, emoji: "👜", bg: "#fecaca", desc: "Roomy work-to-weekend tote with an interior pocket." },
  { id: 33, name: "High-Rise Straight Jeans", store: "Nordstrom", cat: "Fashion", price: 98.0, emoji: "👖", bg: "#bae6fd", desc: "Non-stretch rigid denim in a classic wash." },
  { id: 34, name: "Photocard Binder Set", store: "A-Kpop", cat: "K-pop", price: 18.5, emoji: "📒", bg: "#fbcfe8", desc: "A5 binder with 20 sleeves and a cute cover." },
  { id: 35, name: "Official Lightstick", store: "A-Kpop", cat: "K-pop", price: 42.0, emoji: "🪄", bg: "#ddd6fe", desc: "Bluetooth-enabled light for concerts, in a signature color." },
  { id: 36, name: "Album (Random Version)", store: "A-Kpop", cat: "K-pop", price: 24.9, emoji: "💿", bg: "#c7d2fe", desc: "Photobook, CD, poster and a random photocard." },
  { id: 37, name: "Concert Photo Poster Pack", store: "A-Kpop", cat: "K-pop", price: 12.0, emoji: "🖼️", bg: "#fde68a", desc: "Set of 6 glossy posters." },
  { id: 38, name: "Fan Club Membership Kit", store: "A-Kpop", cat: "K-pop", price: 38.0, emoji: "🎫", bg: "#a7f3d0", desc: "Welcome kit with a member card and exclusive goodies." },
  { id: 39, name: "Plush Doll (20cm)", store: "Cokodive", cat: "K-pop", price: 21.0, emoji: "🧸", bg: "#fed7aa", desc: "Squishy character plush inspired by idol mascots." },
  { id: 40, name: "Acrylic Standee", store: "Cokodive", cat: "K-pop", price: 14.9, emoji: "🌟", bg: "#bae6fd", desc: "Desk-sized standee with a display base." },
  { id: 41, name: "Photocard Toploader 50pk", store: "Cokodive", cat: "K-pop", price: 9.5, emoji: "🃏", bg: "#ddd6fe", desc: "Hard sleeves to keep your cards flat and safe." },
  { id: 42, name: "Fan Slogan Banner", store: "Cokodive", cat: "K-pop", price: 16.0, emoji: "🚩", bg: "#fecaca", desc: "Soft cloth banner for fan events." },
  { id: 43, name: "Keyring & Badge Set", store: "Cokodive", cat: "K-pop", price: 11.9, emoji: "🔑", bg: "#fbcfe8", desc: "Six-piece pack of keyrings and pin badges." },
  { id: 44, name: "Vitamin C Brightening Serum", store: "Sephora", cat: "Skincare", price: 48.0, emoji: "🍊", bg: "#fde68a", desc: "Antioxidant serum for glowy skin." },
  { id: 45, name: "Ceramide Moisturizing Cream", store: "Sephora", cat: "Skincare", price: 36.0, emoji: "🧴", bg: "#bfdbfe", desc: "Rich barrier cream for dry skin." },
  { id: 46, name: "Mineral SPF 50 Sunscreen", store: "Sephora", cat: "Skincare", price: 34.0, emoji: "☀️", bg: "#fed7aa", desc: "Lightweight sun protection with no white cast." },
  { id: 47, name: "Retinol Night Treatment", store: "Sephora", cat: "Skincare", price: 62.0, emoji: "🌙", bg: "#c7d2fe", desc: "Smooths fine lines while you sleep." },
  { id: 48, name: "Clay Detox Face Mask", store: "Sephora", cat: "Skincare", price: 29.0, emoji: "🫧", bg: "#bbf7d0", desc: "Deep-cleans pores in ten minutes." },
  { id: 49, name: "Snail Mucin Essence", store: "Olive Young", cat: "Skincare", price: 21.0, emoji: "🐌", bg: "#e7d5c3", desc: "Bouncy K-beauty essence that hydrates and soothes." },
  { id: 50, name: "Sheet Mask 10-Pack", store: "Olive Young", cat: "Skincare", price: 15.0, emoji: "🎭", bg: "#fbcfe8", desc: "Assorted hydrating masks for weekly self-care." },
  { id: 51, name: "Centella Calming Toner", store: "Olive Young", cat: "Skincare", price: 19.5, emoji: "🌿", bg: "#bbf7d0", desc: "Gentle toner for sensitive skin." },
  { id: 52, name: "Rice Water Cleansing Balm", store: "Olive Young", cat: "Skincare", price: 17.0, emoji: "🍚", bg: "#ddd6fe", desc: "Melts makeup and sunscreen in seconds." },
  { id: 53, name: "Tinted Lip Tint Trio", store: "Olive Young", cat: "Skincare", price: 16.0, emoji: "💄", bg: "#fecaca", desc: "Juicy watery tints in three shades." }
];
